from __future__ import annotations

import json

from pypproxy.store.models import Entry


def generate_request_logger(entries: list[Entry], target: str = "okhttp3") -> str:
    """Generate a Frida script to log all requests to observed hosts/paths."""
    hosts = sorted({e.host for e in entries if e.host})
    endpoints = sorted({(e.method, e.path) for e in entries if e.method and e.path})

    lines = [
        "// Request logger - Generated by pypproxy",
        '"use strict";',
        "",
    ]

    if target == "okhttp3":
        lines += _okhttp3_logger(hosts, endpoints)
    elif target == "nsurlsession":
        lines += _nsurlsession_logger(hosts, endpoints)
    elif target == "fetch":
        lines += _fetch_logger(hosts, endpoints)

    return "\n".join(lines)


def _okhttp3_logger(hosts: list[str], endpoints: list[tuple[str, str]]) -> list[str]:
    return [
        "Java.perform(function() {",
        "    // Hook OkHttp3 for request/response logging",
        "    try {",
        "        const OkHttpClient = Java.use('okhttp3.OkHttpClient');",
        "        const chain = Java.use('okhttp3.Interceptor$Chain');",
        "",
        "        OkHttpClient.newCall.implementation = function(request) {",
        "            const url = request.url().toString();",
        "            const method = request.method();",
        "            let body = '';",
        "            try {",
        "                const rb = request.body();",
        "                if (rb !== null) {",
        "                    const buffer = Java.use('okio.Buffer').$new();",
        "                    rb.writeTo(buffer);",
        "                    body = buffer.readUtf8();",
        "                }",
        "            } catch(e) {}",
        "            console.log('[pypproxy] >>> ' + method + ' ' + url);",
        "            if (body) console.log('[pypproxy] body: ' + body.substring(0, 500));",
        "            const call = this.newCall(request);",
        "            return call;",
        "        };",
        "        console.log('[+] OkHttp3 newCall hooked');",
        "    } catch(e) { console.log('[-] OkHttp3: ' + e); }",
        "",
        "    // Observed hosts:",
        *[f"    // {h}" for h in hosts[:10]],
        "});",
    ]


def _nsurlsession_logger(hosts: list[str], endpoints: list[tuple[str, str]]) -> list[str]:
    return [
        "if (ObjC.available) {",
        "    // Hook NSURLSession for request/response logging",
        "    const NSURLSession = ObjC.classes.NSURLSession;",
        "    if (NSURLSession) {",
        "        const dataTask = NSURLSession['- dataTaskWithRequest:completionHandler:'];",
        "        if (dataTask) {",
        "            Interceptor.attach(dataTask.implementation, {",
        "                onEnter: function(args) {",
        "                    const request = new ObjC.Object(args[2]);",
        "                    const url = request.URL().absoluteString().toString();",
        "                    const method = request.HTTPMethod().toString();",
        "                    console.log('[pypproxy] >>> ' + method + ' ' + url);",
        "                    const body = request.HTTPBody();",
        "                    if (body) {",
        "                        const data = ObjC.classes.NSString.alloc()",
        "                            .initWithData_encoding_(body, 4);",
        "                        console.log('[pypproxy] body: ' + data.toString().substring(0, 500));",
        "                    }",
        "                }",
        "            });",
        "            console.log('[+] NSURLSession hooked');",
        "        }",
        "    }",
        "",
        "    // Observed hosts:",
        *[f"    // {h}" for h in hosts[:10]],
        "}",
    ]


def _fetch_logger(hosts: list[str], endpoints: list[tuple[str, str]]) -> list[str]:
    return [
        "// Hook fetch() API (React Native / WebView)",
        "const origFetch = window.fetch;",
        "window.fetch = function(url, options) {",
        "    const method = (options && options.method) || 'GET';",
        "    console.log('[pypproxy] >>> ' + method + ' ' + url);",
        "    if (options && options.body) {",
        "        console.log('[pypproxy] body: ' + JSON.stringify(options.body).substring(0, 500));",
        "    }",
        "    return origFetch.apply(this, arguments).then(function(resp) {",
        "        console.log('[pypproxy] <<< ' + resp.status + ' ' + url);",
        "        return resp;",
        "    });",
        "};",
        "",
        "// Observed hosts:",
        *[f"// {h}" for h in hosts[:10]],
    ]


def generate_parameter_hook(entry: Entry, target: str = "okhttp3") -> str:
    """Generate a Frida hook to intercept and log a specific endpoint."""
    path = entry.path
    method = entry.method
    host = entry.host

    # Try to extract parameter names from JSON body
    param_names: list[str] = []
    if entry.req_body:
        try:
            data = json.loads(entry.req_body)
            if isinstance(data, dict):
                param_names = list(data.keys())
        except Exception:
            pass

    lines = [
        f"// Hook for {method} {host}{path}",
        "// Generated by pypproxy",
        '"use strict";',
        "",
    ]

    if target == "okhttp3":
        lines += [
            "Java.perform(function() {",
            "    const OkHttpClient = Java.use('okhttp3.OkHttpClient');",
            "    OkHttpClient.newCall.implementation = function(request) {",
            "        const url = request.url().toString();",
            f"        if (url.includes('{path}') && request.method() === '{method}') {{",
            "            console.log('[pypproxy] Intercepted: ' + url);",
            *(
                [
                    "            // Extract body parameters",
                    "            try {",
                    "                const rb = request.body();",
                    "                if (rb !== null) {",
                    "                    const buf = Java.use('okio.Buffer').$new();",
                    "                    rb.writeTo(buf);",
                    "                    const bodyStr = buf.readUtf8();",
                    "                    const obj = JSON.parse(bodyStr);",
                    *[
                        f"                    console.log('[pypproxy] {p}: ' + obj['{p}']);"
                        for p in param_names[:5]
                    ],
                    "                }",
                    "            } catch(e) {}",
                ]
                if param_names
                else []
            ),
            "        }",
            "        return this.newCall(request);",
            "    };",
            "});",
        ]
    elif target == "nsurlsession":
        lines += [
            "if (ObjC.available) {",
            "    const NSURLSession = ObjC.classes.NSURLSession;",
            "    const dataTask = NSURLSession['- dataTaskWithRequest:completionHandler:'];",
            "    Interceptor.attach(dataTask.implementation, {",
            "        onEnter: function(args) {",
            "            const req = new ObjC.Object(args[2]);",
            "            const url = req.URL().absoluteString().toString();",
            f"            if (url.includes('{path}')) {{",
            "                console.log('[pypproxy] iOS intercepted: ' + url);",
            "            }",
            "        }",
            "    });",
            "}",
        ]

    return "\n".join(lines)
