from __future__ import annotations

# ---- iOS certificate pinning bypass scripts ----

IOS_BYPASS_NSURLSESSION = """\
// iOS - NSURLSession / TrustKit / AFNetworking certificate pinning bypass
// Generated by pypproxy
// Usage: frida -U -f <bundle_id> -l bypass_ios.js --no-pause

"use strict";

if (ObjC.available) {
    // --- SecTrustEvaluate bypass ---
    try {
        const SecTrustEvaluate = Module.findExportByName("Security", "SecTrustEvaluate");
        if (SecTrustEvaluate) {
            Interceptor.replace(SecTrustEvaluate, new NativeCallback(function(trust, result) {
                const kSecTrustResultProceed = 1;
                Memory.writeU32(result, kSecTrustResultProceed);
                return 0; // errSecSuccess
            }, "int", ["pointer", "pointer"]));
            console.log("[+] SecTrustEvaluate hooked");
        }
    } catch(e) { console.log("[-] SecTrustEvaluate: " + e); }

    // --- SecTrustEvaluateWithError bypass (iOS 12+) ---
    try {
        const SecTrustEvaluateWithError = Module.findExportByName("Security", "SecTrustEvaluateWithError");
        if (SecTrustEvaluateWithError) {
            Interceptor.replace(SecTrustEvaluateWithError, new NativeCallback(function(trust, error) {
                if (error !== null) Memory.writePointer(error, NULL);
                return 1; // true
            }, "bool", ["pointer", "pointer"]));
            console.log("[+] SecTrustEvaluateWithError hooked");
        }
    } catch(e) { console.log("[-] SecTrustEvaluateWithError: " + e); }

    // --- NSURLSession dataTaskWithRequest bypass ---
    try {
        const NSURLSessionConfiguration = ObjC.classes.NSURLSessionConfiguration;
        if (NSURLSessionConfiguration) {
            const method = NSURLSessionConfiguration["- setTLSMinimumSupportedProtocolVersion:"];
            if (method) {
                Interceptor.attach(method.implementation, {
                    onEnter: function(args) {}
                });
            }
        }
    } catch(e) {}

    // --- TrustKit bypass ---
    try {
        const TSKPinningValidator = ObjC.classes.TSKPinningValidator;
        if (TSKPinningValidator) {
            const evalTrust = TSKPinningValidator["- evaluateTrust:forHostname:"];
            if (evalTrust) {
                Interceptor.replace(evalTrust.implementation, new NativeCallback(function() {
                    return 0; // TSKTrustEvaluationSuccess
                }, "int", ["pointer", "pointer", "pointer", "pointer"]));
                console.log("[+] TrustKit TSKPinningValidator hooked");
            }
        }
    } catch(e) {}

    // --- Alamofire / AFNetworking ---
    try {
        const AFSecurityPolicy = ObjC.classes.AFSecurityPolicy;
        if (AFSecurityPolicy) {
            const evalServerTrust = AFSecurityPolicy["- evaluateServerTrust:forDomain:"];
            if (evalServerTrust) {
                Interceptor.replace(evalServerTrust.implementation, new NativeCallback(function() {
                    return 1; // YES
                }, "bool", ["pointer", "pointer", "pointer", "pointer"]));
                console.log("[+] AFSecurityPolicy hooked");
            }
        }
    } catch(e) {}

    console.log("[pypproxy] iOS SSL pinning bypass active");
} else {
    console.log("[-] Objective-C runtime not available");
}
"""

IOS_BYPASS_SWIFTUI = """\
// iOS - Swift / SwiftUI URLSession pinning bypass
// Generated by pypproxy
"use strict";

// Hook URLSession challenge handler
const CFStreamCreatePairWithSocketToHost = Module.findExportByName(null, "CFStreamCreatePairWithSocketToHost");
const SSLHandshake = Module.findExportByName("Security", "SSLHandshake");

if (SSLHandshake) {
    Interceptor.replace(SSLHandshake, new NativeCallback(function(context) {
        const result = this.SSLHandshake(context);
        return 0; // noErr
    }, "int", ["pointer"]));
    console.log("[+] SSLHandshake hooked");
}

// Hook Security framework SSL evaluation
const SSLSetSessionOption = Module.findExportByName("Security", "SSLSetSessionOption");
if (SSLSetSessionOption) {
    Interceptor.attach(SSLSetSessionOption, {
        onEnter: function(args) {
            // kSSLSessionOptionBreakOnServerAuth = 0
            if (args[1].toInt32() === 0) {
                args[2] = ptr(0); // false - don\'t break
            }
        }
    });
}

console.log("[pypproxy] iOS SSL pinning bypass (Swift) active");
"""

# ---- Android certificate pinning bypass scripts ----

ANDROID_BYPASS_OKHTTP = """\
// Android - OkHttp3 / OkHttp2 certificate pinning bypass
// Generated by pypproxy
// Usage: frida -U -f <package_name> -l bypass_android.js --no-pause

"use strict";

Java.perform(function() {

    // --- OkHttp3 CertificatePinner ---
    try {
        const CertificatePinner = Java.use("okhttp3.CertificatePinner");
        CertificatePinner.check.overload("java.lang.String", "java.util.List").implementation = function(hostname, peerCertificates) {
            console.log("[+] OkHttp3 CertificatePinner.check bypassed for: " + hostname);
        };
        console.log("[+] OkHttp3 CertificatePinner hooked");
    } catch(e) { console.log("[-] OkHttp3: " + e.message); }

    // --- OkHttp2 CertificatePinner ---
    try {
        const CertificatePinner2 = Java.use("com.squareup.okhttp.CertificatePinner");
        CertificatePinner2.check.overload("java.lang.String", "java.util.List").implementation = function(hostname, peerCertificates) {
            console.log("[+] OkHttp2 CertificatePinner.check bypassed for: " + hostname);
        };
    } catch(e) {}

    // --- Trustmanager ---
    try {
        const X509TrustManager = Java.use("javax.net.ssl.X509TrustManager");
        const SSLContext = Java.use("javax.net.ssl.SSLContext");

        const TrustManager = Java.registerClass({
            name: "com.pypproxy.TrustManager",
            implements: [X509TrustManager],
            methods: {
                checkClientTrusted: function(chain, authType) {},
                checkServerTrusted: function(chain, authType) {},
                getAcceptedIssuers: function() { return []; }
            }
        });

        const TrustManagers = [TrustManager.$new()];
        const sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, TrustManagers, null);

        const HttpsURLConnection = Java.use("javax.net.ssl.HttpsURLConnection");
        HttpsURLConnection.setDefaultSSLSocketFactory(sslContext.getSocketFactory());
        HttpsURLConnection.setDefaultHostnameVerifier(Java.use("javax.net.ssl.HostnameVerifier").$implement({
            verify: function(hostname, session) { return true; }
        }));
        console.log("[+] TrustManager hooked");
    } catch(e) { console.log("[-] TrustManager: " + e.message); }

    // --- Android Network Security Config bypass ---
    try {
        const NetworkSecurityConfig = Java.use("android.security.net.config.NetworkSecurityConfig");
        if (NetworkSecurityConfig) {
            console.log("[+] NetworkSecurityConfig available - consider using network_security_config.xml");
        }
    } catch(e) {}

    // --- Retrofit / custom pinners ---
    try {
        const PinningTrustManager = Java.use("org.thoughtcrime.ssl.pinning.PinningTrustManager");
        PinningTrustManager.checkServerTrusted.implementation = function(chain, authType) {
            console.log("[+] PinningTrustManager bypassed");
        };
    } catch(e) {}

    console.log("[pypproxy] Android SSL pinning bypass active");
});
"""

ANDROID_BYPASS_FLUTTER = """\
// Android - Flutter ssl_client.cc pinning bypass
// Generated by pypproxy
// Requires: finding ssl_verify_peer_cert offset

"use strict";

function bypass_flutter_ssl() {
    const moduleName = "libflutter.so";
    const module = Process.findModuleByName(moduleName);
    if (!module) {
        console.log("[-] libflutter.so not found");
        return;
    }

    // Search for ssl_verify_peer_cert pattern
    const pattern = "2D E9 F0 4F A3 B0 82 46 50 20 10 70";
    Memory.scan(module.base, module.size, pattern, {
        onMatch: function(address, size) {
            console.log("[+] Found ssl_verify_peer_cert at: " + address);
            Interceptor.replace(address, new NativeCallback(function(ssl, out_alert) {
                console.log("[+] Flutter SSL verification bypassed");
                return 0; // SSL_VERIFY_OK
            }, "int", ["pointer", "pointer"]));
        },
        onComplete: function() {
            console.log("[*] Flutter scan complete");
        }
    });
}

bypass_flutter_ssl();
"""

# ---- Traffic-based hook generator ----


def generate_traffic_hooks(hosts: list[str], endpoints: list[tuple[str, str]]) -> str:
    """Generate Frida hooks for observed API endpoints."""
    hooks: list[str] = []
    hooks.append("// API traffic hooks - Generated by pypproxy")
    hooks.append('"use strict";')
    hooks.append("")
    hooks.append("Java.perform(function() {")
    hooks.append('    const OkHttpClient = Java.use("okhttp3.OkHttpClient");')
    hooks.append('    const Request = Java.use("okhttp3.Request");')
    hooks.append('    const Response = Java.use("okhttp3.Response");')
    hooks.append("")
    hooks.append("    // Hook OkHttp3 newCall to intercept all requests")
    hooks.append("    OkHttpClient.newCall.implementation = function(request) {")
    hooks.append("        const url = request.url().toString();")
    hooks.append("        const method = request.method();")
    hooks.append("")

    if endpoints:
        hooks.append("        // Log observed endpoints")
        for method, path in sorted(set(endpoints))[:20]:
            escaped = path.replace("'", "\\'")
            hooks.append(f"        if (url.includes('{escaped}') && method === '{method}') {{")
            hooks.append(f"            console.log('[pypproxy] {method} {path}: ' + url);")
            hooks.append("        }")
        hooks.append("")

    hooks.append("        const result = this.newCall(request);")
    hooks.append("        return result;")
    hooks.append("    };")
    hooks.append("")

    if hosts:
        hooks.append("    // Observed hosts:")
        for host in sorted(set(hosts))[:10]:
            hooks.append(f"    //   {host}")

    hooks.append("});")
    return "\n".join(hooks)


# ---- Template collection ----

TEMPLATES = {
    "iOS SSL Bypass (NSURLSession)": IOS_BYPASS_NSURLSESSION,
    "iOS SSL Bypass (Swift)": IOS_BYPASS_SWIFTUI,
    "Android SSL Bypass (OkHttp)": ANDROID_BYPASS_OKHTTP,
    "Android SSL Bypass (Flutter)": ANDROID_BYPASS_FLUTTER,
}


def get_template(name: str) -> str:
    return TEMPLATES.get(name, f"// Template '{name}' not found")


def list_templates() -> list[str]:
    return list(TEMPLATES.keys())
